import { useRef, useState } from 'react'
import { AnswerViz } from './AnswerViz.jsx'

/**
 * BriefingStrip — IBM Granite daily signal briefing + preset question chips.
 *
 * Layout: two columns inside a single card.
 *   Left  — auto-generated signal briefing (existing behaviour).
 *   Right — three preset question chips; clicking one fires a POST /ask call
 *           and renders the answer below, replacing the previous answer.
 *
 * The question answer panel is scoped entirely to this component — no view-model
 * state is needed because the user is making an ad-hoc read, not a data-load
 * that other panels depend on.
 *
 * Hidden entirely when briefing.text is null (watsonx not configured).
 */
export function BriefingStrip({ briefing, apiClient }) {
  const [activeQuestion, setActiveQuestion] = useState(null) // question_id | null
  const [answerState, setAnswerState] = useState('idle')     // 'idle' | 'loading' | 'done' | 'error'
  const [answerText, setAnswerText] = useState(null)
  const [answerResult, setAnswerResult] = useState(null)     // full API response incl. chart_data
  const abortRef = useRef(null)

  // Derive a stable client reference from the prop (parent passes DashboardApiClient).
  const client = apiClient ?? null

  async function handleChipClick(questionId) {
    // Clicking the active chip a second time dismisses the answer.
    if (activeQuestion === questionId && answerState !== 'loading') {
      dismiss()
      return
    }

    setActiveQuestion(questionId)
    setAnswerText(null)
    setAnswerResult(null)
    setAnswerState('loading')

    try {
      if (!client) throw new Error('No API client available')
      const result = await client.askPresetQuestion(questionId)
      if (result.answer) {
        setAnswerText(result.answer)
        setAnswerResult(result)
        setAnswerState('done')
      } else {
        setAnswerText(result.unavailable_reason ?? 'No answer returned.')
        setAnswerResult(null)
        setAnswerState('error')
      }
    } catch (err) {
      setAnswerText(err.message ?? 'Request failed.')
      setAnswerResult(null)
      setAnswerState('error')
    }
  }

  // Dismiss state also clears the result
  function dismiss() {
    setActiveQuestion(null)
    setAnswerText(null)
    setAnswerResult(null)
    setAnswerState('idle')
  }

  // Render nothing when the main briefing is unavailable (watsonx not configured).
  if (!briefing || !briefing.text) return null

  return (
    <aside className="briefing-strip" aria-label="AI signal briefing">
      <div className="briefing-strip__inner">
        {/* ── Top label row ──────────────────────────────────────── */}
        <div className="briefing-strip__label-row">
          <span className="briefing-strip__eyebrow">Signal Briefing</span>
          <span className="briefing-strip__badge">
            <GraniteIcon />
            Generated by IBM Granite
          </span>
          {briefing.cached && (
            <span className="briefing-strip__cached-pill">cached</span>
          )}
        </div>

        {/* ── Two-column body ────────────────────────────────────── */}
        <div className="briefing-strip__body">
          {/* Left: auto briefing prose */}
          <div className="briefing-strip__prose-col">
            <p className="briefing-strip__text">{briefing.text}</p>
            {briefing.as_of && (
              <p className="briefing-strip__meta">As of {briefing.as_of}</p>
            )}
          </div>

          {/* Right: preset question chips */}
          <div className="briefing-strip__ask-col">
            <p className="briefing-strip__ask-label">Ask Granite</p>
            <div className="briefing-strip__chips">
              {PRESET_QUESTIONS.map(({ id, label }) => (
                <button
                  key={id}
                  type="button"
                  className={[
                    'briefing-chip',
                    activeQuestion === id ? 'briefing-chip--active' : '',
                    answerState === 'loading' && activeQuestion === id
                      ? 'briefing-chip--loading'
                      : '',
                  ]
                    .filter(Boolean)
                    .join(' ')}
                  onClick={() => handleChipClick(id)}
                  disabled={answerState === 'loading' && activeQuestion !== id}
                  aria-pressed={activeQuestion === id}
                >
                  {answerState === 'loading' && activeQuestion === id ? (
                    <span className="briefing-chip__spinner" aria-hidden="true" />
                  ) : null}
                  {label}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* ── Answer panel — prose left, viz right ───────────────── */}
        {activeQuestion && answerState !== 'idle' && (
          <div
            className={[
              'briefing-strip__answer',
              answerState === 'loading' ? 'briefing-strip__answer--loading' : '',
              answerState === 'error'   ? 'briefing-strip__answer--error'   : '',
            ]
              .filter(Boolean)
              .join(' ')}
          >
            {answerState === 'loading' ? (
              <AnswerSkeleton />
            ) : (
              <div className="briefing-strip__answer-body">
                <div className="briefing-strip__answer-prose">
                  <p className="briefing-strip__answer-label">
                    {PRESET_QUESTIONS.find((q) => q.id === activeQuestion)?.label}
                  </p>
                  <p className="briefing-strip__answer-text">{answerText}</p>
                </div>
                {answerResult?.chart_data && (
                  <div className="briefing-strip__answer-viz">
                    <AnswerViz
                      questionId={activeQuestion}
                      chartData={answerResult.chart_data}
                    />
                  </div>
                )}
              </div>
            )}
          </div>
        )}
      </div>
    </aside>
  )
}

/** Three preset questions — label is what appears on the chip. */
const PRESET_QUESTIONS = [
  { id: 'eia_interpretation', label: 'Latest EIA release' },
  { id: 'cot_interpretation', label: 'COT positioning' },
  { id: 'margin_drivers',     label: 'Margin drivers' },
]

/** Three pulsing skeleton lines while Granite is thinking. */
function AnswerSkeleton() {
  return (
    <div className="briefing-skeleton" aria-label="Loading answer…">
      <div className="briefing-skeleton__line briefing-skeleton__line--wide" />
      <div className="briefing-skeleton__line briefing-skeleton__line--mid" />
      <div className="briefing-skeleton__line briefing-skeleton__line--narrow" />
    </div>
  )
}

/** Minimal inline IBM star icon — no external asset dependency. */
function GraniteIcon() {
  return (
    <svg
      className="briefing-strip__icon"
      width="13"
      height="13"
      viewBox="0 0 24 24"
      fill="none"
      aria-hidden="true"
    >
      <path
        d="M12 2L15.09 8.26L22 9.27L17 14.14L18.18 21.02L12 17.77L5.82 21.02L7 14.14L2 9.27L8.91 8.26L12 2Z"
        fill="#0f62fe"
        stroke="#0f62fe"
        strokeWidth="1"
        strokeLinejoin="round"
      />
    </svg>
  )
}
