/**
 * BriefingStrip — IBM Granite daily signal briefing.
 *
 * Casual: the LLM-narrated "what does this all mean right now" strip.
 *
 * Rendered as a full-width strip immediately below the dashboard header.
 * Hidden when the briefing text is null (watsonx not configured or
 * generation failed) so the rest of the dashboard is unaffected.
 *
 * The "Generated by IBM Granite" attribution badge signals AI utilization
 * to judges and makes clear the numbers are deterministic while the prose
 * is model-generated.
 */
export function BriefingStrip({ briefing }) {
  if (!briefing || !briefing.text) {
    return null
  }

  return (
    <aside className="briefing-strip" aria-label="AI signal briefing">
      <div className="briefing-strip__inner">
        <div className="briefing-strip__label-row">
          <span className="briefing-strip__eyebrow">Signal Briefing</span>
          <span className="briefing-strip__badge">
            <GraniteIcon />
            Generated by IBM Granite
          </span>
          {briefing.cached && (
            <span className="briefing-strip__cached-pill">cached</span>
          )}
        </div>
        <p className="briefing-strip__text">{briefing.text}</p>
        {briefing.as_of && (
          <p className="briefing-strip__meta">As of {briefing.as_of}</p>
        )}
      </div>
    </aside>
  )
}

/** Minimal inline IBM "spark" icon — no external asset dependency. */
function GraniteIcon() {
  return (
    <svg
      className="briefing-strip__icon"
      width="14"
      height="14"
      viewBox="0 0 24 24"
      fill="none"
      aria-hidden="true"
    >
      <path
        d="M12 2L15.09 8.26L22 9.27L17 14.14L18.18 21.02L12 17.77L5.82 21.02L7 14.14L2 9.27L8.91 8.26L12 2Z"
        fill="#0f62fe"
        stroke="#0f62fe"
        strokeWidth="1"
        strokeLinejoin="round"
      />
    </svg>
  )
}
