/**
 * Methodology footer explaining CARD formula and limitations.
 */
export function MethodologyFooter() {
  return (
    <footer className="methodology-footer">
      <h2>How this dashboard works</h2>
      <p>
        Simplified Iowa State CARD dry-mill model: 1 bushel of corn plus 72.8k BTU
        natural gas produces 2.8 gallons ethanol, 17 lbs DDGS, and 0.7 lbs corn oil.
        The plant margin also credits <strong>D6 RIN revenue</strong> (1 RIN per gallon
        of ethanol) — often the largest single revenue line at current RIN prices.
        The CME-standard crush spread is <em>physical only</em> (2.8 × ethanol − corn)
        and is shown separately from the full plant P&amp;L. DDGS is quoted in{' '}
        <strong>$/short ton</strong> throughout the UI.
      </p>
      <p>
        Prices: <strong>ethanol/corn/RBOB/nat gas</strong> from CBOT + NYMEX front-month
        futures (Yahoo Finance).{' '}
        <strong>Ethanol production and stocks</strong> from EIA weekly.{' '}
        <strong>D6 RIN prices</strong> from EPA EMTS via weekly CSV file-drop.{' '}
        <strong>CFTC COT</strong> for managed-money positioning from CFTC Socrata,
        weekly. This is a decision-support tool, not an institutional margin model —
        mixed bases and seeded fallbacks may apply when a live feed is unavailable.
      </p>
      <p>
        Z-score bands: Rich &gt; +1.5, Elevated +1 to +1.5, Normal −1 to +1, Soft −1.5
        to −1, Weak &lt; −1.5. Negative margins are shown as-is. Warning rules use
        20th/80th percentile thresholds over a rolling 180-day window; each firing is
        point-in-time backtested with a 30-day event cooldown.
      </p>
      <p>
        The <strong>Signal Briefing</strong> strip and <strong>Ask Granite</strong>{' '}
        answers are generated by IBM Granite on watsonx.ai, grounded in the exact
        structured numbers computed above — the model narrates, it does not calculate.
      </p>
    </footer>
  )
}
