/**
 * Methodology footer explaining CARD formula and limitations.
 */
export function MethodologyFooter() {
  return (
    <footer className="methodology-footer">
      <h2>How this dashboard works</h2>
      <p>
        Simplified Iowa State CARD dry-mill model: 1 bushel of corn plus 72.8k BTU
        natural gas produces 2.8 gallons ethanol, 17 lbs DDGS, and 0.7 lbs corn oil.
        The <strong>plant operating margin</strong> is physical only — ethanol,
        DDGS, and corn oil revenue minus corn, natural gas, and misc opex costs.
        DDGS is quoted in <strong>$/short ton</strong> throughout the UI.
      </p>
      <p>
        <strong>D6 RIN treatment.</strong> D6 prices come from EPA RIN
        transaction-price data. The dashboard converts the D6 price into a
        per-bushel <strong>regulatory-value equivalent</strong> using the modeled
        ethanol yield (~$1.99/RIN × 2.8 gal/bu ≈ $5.57/bu). This is the scale of
        the compliance credit associated with the ethanol output — shown
        separately from the plant operating margin. The model does <em>not</em>{' '}
        assume producers capture the full quoted RIN value dollar-for-dollar;
        actual producer capture depends on pass-through economics between
        producers and obligated parties, which is out of scope here.
      </p>
      <p>
        <strong>Simple ethanol/corn spread.</strong> The Financial panel's
        two-leg spread is <em>ethanol value per bushel minus corn cost</em>{' '}
        (2.8 × ethanol − corn). This is a simplified market-spread screen; it is
        NOT the CME/CBOT-listed corn-for-ethanol crush and should not be read
        as a complete plant margin. Coproducts, operating costs, and D6 RIN
        value are all excluded.
      </p>
      <p>
        Prices: <strong>ethanol/corn/RBOB/nat gas</strong> from CBOT + NYMEX front-month
        futures (Yahoo Finance).{' '}
        <strong>Ethanol production and stocks</strong> from EIA weekly.{' '}
        <strong>D6 RIN prices</strong> from EPA EMTS via weekly CSV file-drop.{' '}
        <strong>CFTC COT</strong> for managed-money positioning from CFTC Socrata,
        weekly. This is a decision-support tool, not an institutional margin model —
        mixed bases and seeded fallbacks may apply when a live feed is unavailable.
      </p>
      <p>
        Z-score bands: Rich &gt; +1.5, Elevated +1 to +1.5, Normal −1 to +1, Soft −1.5
        to −1, Weak &lt; −1.5. Negative margins are shown as-is. Warning rules use
        20th/80th percentile thresholds over a rolling 180-day window; each firing is
        point-in-time backtested with a 30-day event cooldown.
      </p>
      <p>
        The <strong>Signal Briefing</strong> strip and <strong>Ask Granite</strong>{' '}
        answers are generated by IBM Granite on watsonx.ai, grounded in the exact
        structured numbers computed above — the model narrates, it does not calculate.
      </p>
    </footer>
  )
}
